
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gl_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: hruser
    password: HrSystem2024\!
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

# 阿里云OSS配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID:your-access-key-id}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET:your-access-key-secret}
    bucket-name: big-eventhr

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #自动驼峰映射，默认为true，可不写
    #导入日志实现类，开启数据库访问日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl